version: '3.8'

services:
    postgres:
        image: postgres:13
        container_name: my_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123123
            POSTGRES_DB: my_site
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_data:
